"use client";

import { useState } from "react";
import CollectionBook from "@/components/CollectionBook";
import FighterCard from "@/components/FighterCard";
import HarvestedCropCard from "@/components/HarvestedCropCard";
import TeamSelector from "@/components/TeamSelector";
import HelpButton from "@/components/HelpButton";
import { AWAKENING_COSTS } from "@/lib/awakening";
import { ASCENSION_HARD_PITY, FUSION_UPGRADE_CHANCE, getFusionEligibility } from "@/lib/fusion";
import { crops, mutations } from "@/lib/game-data";
import { FUSION_RARITIES, FUSION_SPECIES, filterFighterRoster, getFusionRosterGroups, getReleaseConfirmationCount } from "@/lib/fighter-roster";
import { ASCENDED_DISMANTLE_SHARDS, getDismantleConfirmationCount } from "@/lib/ascendant-shards";
import { presetToActiveTeam } from "@/lib/team-selection";
import type { AscensionPity, CollectionEntry, CropType, Fighter, HarvestedCrop, HarvestMutationType, MutationType, TeamPresetIndex, TeamPresets } from "@/lib/game-types";
import type { GuideTopicId } from "@/lib/guide-data";

const nextTier: Record<HarvestMutationType, string> = { normal: "Large", large: "Golden", golden: "Prismatic", prismatic: "Ascended" };
type FarmhouseTab = "collection" | "fighters" | "active team" | "harvested crops" | "fusion";
type Props = { collection: CollectionEntry[]; coins: number; fighters: Fighter[]; teamPresets: TeamPresets; defaultTeamPreset: TeamPresetIndex; ascendantShards: number; ascensionPity: AscensionPity; harvestedCrops: HarvestedCrop[]; awakenCrop: (itemId: string) => void; fuseFighters: (selectedIds: string[]) => Fighter | null; setFighterLocked: (fighterId: string, locked: boolean) => boolean; setFighterFavorite: (fighterId: string, favorite: boolean) => boolean; renameFighter: (fighterId: string, name: string) => boolean; releaseFighter: (fighterId: string) => boolean; dismantleFighter: (fighterId: string) => boolean; setTeamPreset: (index: TeamPresetIndex, fighterIds: string[]) => boolean; renameTeamPreset: (index: TeamPresetIndex, name: string) => boolean; setDefaultTeamPreset: (index: TeamPresetIndex) => void; onHelp: (topic: GuideTopicId) => void; onClose: () => void };

export default function WorldFarmhouseOverlay({ collection, coins, fighters, teamPresets, defaultTeamPreset, ascendantShards, ascensionPity, harvestedCrops, awakenCrop, fuseFighters, setFighterLocked, setFighterFavorite, renameFighter, releaseFighter, dismantleFighter, setTeamPreset, renameTeamPreset, setDefaultTeamPreset, onHelp, onClose }: Props) {
  const [tab, setTab] = useState<FarmhouseTab>("collection");
  const [selectedIds, setSelectedIds] = useState<string[]>([]);
  const [fusionResult, setFusionResult] = useState<Fighter | null>(null);
  const [openGroup, setOpenGroup] = useState<{ mutation: MutationType; crop: CropType } | null>(null);
  const [releaseConfirmation, setReleaseConfirmation] = useState<{ fighterId: string; step: number } | null>(null);
  const [dismantleConfirmation, setDismantleConfirmation] = useState<{ fighterId: string; step: number } | null>(null);
  const existingIds = new Set(fighters.map((fighter) => fighter.id));
  const selected = selectedIds.filter((id) => existingIds.has(id));
  const eligibility = getFusionEligibility(fighters, selected);
  const firstSelected = fighters.find((fighter) => fighter.id === selected[0]);
  const groups = getFusionRosterGroups(fighters);
  const activeGroup = openGroup ? groups.find((group) => group.mutation === openGroup.mutation && group.crop === openGroup.crop) ?? null : null;

  function toggleFighter(id: string) {
    const fighter = fighters.find((entry) => entry.id === id);
    if (!fighter || fighter.locked || fighter.mutation === "ascended") return;
    setFusionResult(null);
    setSelectedIds((current) => { const valid = current.filter((selectedId) => existingIds.has(selectedId)); return valid.includes(id) ? valid.filter((selectedId) => selectedId !== id) : valid.length < 4 ? [...valid, id] : valid; });
  }
  function performFusion() { if (!eligibility.valid) return; const result = fuseFighters(selected); if (result) { setSelectedIds([]); setFusionResult(result); } }
  function confirmRelease() {
    if (!releaseConfirmation) return;
    const fighter = fighters.find((entry) => entry.id === releaseConfirmation.fighterId);
    if (!fighter || fighter.locked) { setReleaseConfirmation(null); return; }
    if (releaseConfirmation.step < getReleaseConfirmationCount(fighter.mutation)) { setReleaseConfirmation({ ...releaseConfirmation, step: releaseConfirmation.step + 1 }); return; }
    releaseFighter(fighter.id); setSelectedIds((current) => current.filter((id) => id !== fighter.id)); setReleaseConfirmation(null);
  }
  function closeFarmhouse() { setSelectedIds([]); setFusionResult(null); setReleaseConfirmation(null); setDismantleConfirmation(null); onClose(); }

  return <div className="absolute inset-0 z-[70] flex items-center justify-center bg-black/65 p-2 sm:p-5" role="dialog" aria-modal="true" aria-labelledby="farmhouse-title">
    <section className="relative flex max-h-full w-full max-w-4xl flex-col overflow-hidden rounded-2xl border-2 border-[#765438] bg-[#efe2b8] text-[#2f3e2f] shadow-2xl">
      <header className="flex shrink-0 items-center justify-between gap-3 border-b-2 border-[#765438]/35 bg-[#d8b875] px-4 py-3"><div><h2 id="farmhouse-title" className="text-xl font-bold sm:text-2xl">Farmhouse</h2><p className="text-xs opacity-70 sm:text-sm">Your discoveries and awakened fighters.</p></div><button type="button" onClick={closeFarmhouse} className="rounded-lg bg-[#fff8dc] px-3 py-2 font-bold shadow-sm hover:bg-white">Close</button></header>
      <div className="flex shrink-0 gap-2 overflow-x-auto border-b border-[#765438]/25 bg-[#e5cf98] px-3 pt-3" role="tablist" aria-label="Farmhouse sections">{(["collection", "fighters", "active team", "harvested crops", "fusion"] as FarmhouseTab[]).map((value) => <button key={value} type="button" role="tab" aria-selected={tab === value} onClick={() => { setTab(value); setReleaseConfirmation(null); }} className={`shrink-0 rounded-t-lg px-3 py-2 text-sm font-bold capitalize ${tab === value ? "bg-[#fff8dc]" : "bg-[#c8aa6a] hover:bg-[#d4ba80]"}`}>{value}{value === "fighters" ? ` (${fighters.length})` : value === "harvested crops" ? ` (${harvestedCrops.length})` : ""}</button>)}</div>
      <div className="min-h-0 flex-1 overflow-y-auto p-3 sm:p-5">
        {tab === "collection" ? <CollectionBook collection={collection} /> : tab === "active team" ? <TeamPresetsEditor fighters={fighters} presets={teamPresets} defaultIndex={defaultTeamPreset} setTeamPreset={setTeamPreset} renameTeamPreset={renameTeamPreset} setDefaultTeamPreset={setDefaultTeamPreset} onHelp={onHelp} /> : tab === "harvested crops" ? <HarvestedSection coins={coins} items={harvestedCrops} awakenCrop={awakenCrop} onHelp={onHelp} /> : tab === "fusion" ? <FusionPanel groups={groups} activeGroup={activeGroup} setOpenGroup={(group) => { setOpenGroup(group); setSelectedIds([]); setFusionResult(null); }} selected={selected} firstSelected={firstSelected} eligibility={eligibility} fusionResult={fusionResult} ascensionPity={ascensionPity} toggleFighter={toggleFighter} performFusion={performFusion} clear={() => setSelectedIds([])} onHelp={onHelp} /> : <Roster fighters={fighters} shards={ascendantShards} setFighterLocked={setFighterLocked} setFighterFavorite={setFighterFavorite} renameFighter={renameFighter} requestRelease={(fighterId) => setReleaseConfirmation({ fighterId, step: 1 })} requestDismantle={(fighterId) => setDismantleConfirmation({ fighterId, step: 1 })} />}
      </div>
      {releaseConfirmation && <ReleaseConfirmation fighters={fighters} confirmation={releaseConfirmation} onConfirm={confirmRelease} onCancel={() => setReleaseConfirmation(null)} />}
      {dismantleConfirmation && <DismantleConfirmation fighters={fighters} confirmation={dismantleConfirmation} onConfirm={() => { const fighter = fighters.find((entry) => entry.id === dismantleConfirmation.fighterId); if (!fighter || fighter.locked) return setDismantleConfirmation(null); if (dismantleConfirmation.step < getDismantleConfirmationCount(fighter.favorite)) return setDismantleConfirmation({ ...dismantleConfirmation, step: dismantleConfirmation.step + 1 }); dismantleFighter(fighter.id); setDismantleConfirmation(null); }} onCancel={() => setDismantleConfirmation(null)} />}
    </section>
  </div>;
}

function TeamPresetsEditor({ fighters, presets, defaultIndex, setTeamPreset, renameTeamPreset, setDefaultTeamPreset, onHelp }: { fighters: Fighter[]; presets: TeamPresets; defaultIndex: TeamPresetIndex; setTeamPreset: (index: TeamPresetIndex, ids: string[]) => boolean; renameTeamPreset: (index: TeamPresetIndex, name: string) => boolean; setDefaultTeamPreset: (index: TeamPresetIndex) => void; onHelp: (topic: GuideTopicId) => void }) {
  const [index, setIndex] = useState<TeamPresetIndex>(defaultIndex);
  const preset = presets[index]; const selected = presetToActiveTeam(preset).map((id) => id ?? "");
  return <div className="rounded-xl bg-[#fff8dc] p-4"><div className="flex items-center gap-2"><h3 className="text-lg font-black">Team Presets</h3><HelpButton topic="active-team" onOpen={onHelp} /></div><p className="text-sm">Save three ordered teams. Locked fighters are allowed, and the default prefills Dungeon and PvP.</p><div className="mt-3 flex flex-wrap gap-2">{presets.map((entry, presetIndex) => <button key={presetIndex} type="button" onClick={() => setIndex(presetIndex as TeamPresetIndex)} className={`rounded-lg px-3 py-2 text-sm font-bold ${index === presetIndex ? "bg-[#4f772d] text-white" : "border border-[#765438]/40"}`}>{entry.name}{defaultIndex === presetIndex ? " ★" : ""}</button>)}</div><div className="mt-3 flex flex-wrap gap-2"><input aria-label="Preset name" value={preset.name} maxLength={20} onChange={(event) => renameTeamPreset(index, event.target.value)} className="min-w-0 flex-1 rounded-lg border border-[#765438]/35 bg-white/70 px-3 py-2 font-bold" /><button type="button" onClick={() => setDefaultTeamPreset(index)} disabled={defaultIndex === index} className="rounded-lg border border-[#765438]/40 px-3 py-2 text-sm font-bold disabled:opacity-45">{defaultIndex === index ? "Default" : "Set Default"}</button></div><TeamSelector fighters={fighters} selected={selected} onSelect={(ids) => setTeamPreset(index, ids)} locked={false} />{selected.some((id) => !id) && <p className="mt-2 text-sm font-bold text-[#8b2f24]">This preset is incomplete and will not prefill battles.</p>}</div>;
}
function HarvestedSection({ coins, items, awakenCrop, onHelp }: { coins: number; items: HarvestedCrop[]; awakenCrop: (id: string) => void; onHelp: (topic: GuideTopicId) => void }) {
  if (!items.length) return <div><div className="mb-3 flex items-center gap-2"><h3 className="text-lg font-black">Awakening</h3><HelpButton topic="awakening" onOpen={onHelp} /></div><div className="rounded-xl bg-[#fff8dc] p-5 text-sm opacity-70">Harvest crops before awakening them into fighters.</div></div>;
  return <div><div className="mb-3 flex items-center gap-2"><h3 className="text-lg font-black">Awakening</h3><HelpButton topic="awakening" onOpen={onHelp} /></div><div className="grid grid-cols-1 gap-3 sm:grid-cols-2">{items.map((item) => { const cost = AWAKENING_COSTS[item.mutation]; const shortfall = Math.max(0, cost - coins); return <HarvestedCropCard key={item.id} item={item} actionLabel="Awaken" actionDetail={shortfall ? `Cost: ${cost} · Need ${shortfall} more` : `Cost: ${cost} coins`} actionDisabled={shortfall > 0} onAction={awakenCrop} />; })}</div></div>;
}

function Roster({ fighters, shards, setFighterLocked, setFighterFavorite, renameFighter, requestRelease, requestDismantle }: { fighters: Fighter[]; shards: number; setFighterLocked: (id: string, locked: boolean) => boolean; setFighterFavorite: (id: string, favorite: boolean) => boolean; renameFighter: (id: string, name: string) => boolean; requestRelease: (id: string) => void; requestDismantle: (id: string) => void }) {
  const [rarity, setRarity] = useState<"all" | "favorites" | MutationType>("all"); const [species, setSpecies] = useState<"all" | CropType>("all");
  if (!fighters.length) return <div className="rounded-xl bg-[#fff8dc] p-5 text-sm opacity-70">Awaken a harvested crop to create your first fighter.</div>;
  const visible = filterFighterRoster(fighters, rarity, species);
  return <div><div className="mb-3 rounded-xl bg-[#fff8dc] p-3"><div className="flex flex-wrap items-center justify-between gap-2"><strong>Roster · {visible.length}/{fighters.length}</strong><span className="text-sm font-black">Ascendant Shards: {shards}</span></div><div className="mt-2 flex gap-2 overflow-x-auto">{(["all", "favorites", "ascended", "prismatic", "golden", "large", "normal"] as const).map((value) => <button key={value} type="button" onClick={() => setRarity(value)} className={`shrink-0 rounded-lg px-2 py-1 text-xs font-bold capitalize ${rarity === value ? "bg-[#4f772d] text-white" : "border border-[#765438]/35"}`}>{value}</button>)}</div><div className="mt-2 flex gap-2">{(["all", "potato", "carrot", "corn"] as const).map((value) => <button key={value} type="button" onClick={() => setSpecies(value)} className={`rounded-lg px-2 py-1 text-xs font-bold capitalize ${species === value ? "bg-[#765438] text-white" : "border border-[#765438]/35"}`}>{value}</button>)}</div></div><div className="grid grid-cols-1 gap-3 sm:grid-cols-2">{visible.map((fighter) => <div key={fighter.id} className="rounded-xl bg-[#fff8dc]"><FighterCard fighter={fighter} /><div className="px-4 pb-2"><label className="text-xs font-bold">Name<input defaultValue={fighter.name ?? ""} maxLength={20} placeholder="Add nickname" onBlur={(event) => { if (event.target.value.trim()) renameFighter(fighter.id, event.target.value); }} className="mt-1 block w-full rounded-lg border border-[#765438]/30 bg-white/60 px-2 py-1" /></label></div><div className="flex flex-wrap gap-2 px-4 pb-3"><button type="button" onClick={() => setFighterFavorite(fighter.id, !fighter.favorite)} className="rounded-lg border border-[#765438]/40 px-3 py-1 text-xs font-bold">{fighter.favorite ? "★ Favorite" : "☆ Favorite"}</button><button type="button" onClick={() => setFighterLocked(fighter.id, !fighter.locked)} className="rounded-lg border border-[#765438]/40 px-3 py-1 text-xs font-bold">{fighter.locked ? "🔒 Unlock" : "🔓 Lock"}</button>{fighter.mutation === "ascended" ? <button type="button" onClick={() => requestDismantle(fighter.id)} disabled={fighter.locked} className="rounded-lg border border-[#8b5bb5]/50 px-3 py-1 text-xs font-bold text-[#673a8f] disabled:opacity-40">Dismantle</button> : <button type="button" onClick={() => requestRelease(fighter.id)} disabled={fighter.locked} className="rounded-lg border border-[#9b3d2f]/50 px-3 py-1 text-xs font-bold text-[#8b2f24] disabled:opacity-40">Release</button>}</div></div>)}</div>{!visible.length && <p className="rounded-xl bg-[#fff8dc] p-4 text-sm">No fighters match these filters.</p>}<p className="mt-3 text-xs opacity-65">Ascendant Shards are stored for future cosmetics and special upgrades. They have no gameplay use yet.</p></div>;
}
function FusionPanel({ groups, activeGroup, setOpenGroup, selected, firstSelected, eligibility, fusionResult, ascensionPity, toggleFighter, performFusion, clear, onHelp }: { groups: ReturnType<typeof getFusionRosterGroups>; activeGroup: ReturnType<typeof getFusionRosterGroups>[number] | null; setOpenGroup: (group: { mutation: MutationType; crop: CropType } | null) => void; selected: string[]; firstSelected?: Fighter; eligibility: ReturnType<typeof getFusionEligibility>; fusionResult: Fighter | null; ascensionPity: AscensionPity; toggleFighter: (id: string) => void; performFusion: () => void; clear: () => void; onHelp: (topic: GuideTopicId) => void }) {
  return <div className="relative min-h-full pb-32">
    <div className="mb-3 flex items-center gap-2"><h3 className="text-lg font-black">Fusion</h3><HelpButton topic="fusion" onOpen={onHelp} /></div>
    {fusionResult && <div className="mb-3 rounded-xl border-2 border-[#4f772d] bg-[#e6f3c8] p-3" role="status"><h3 className="mb-2 font-bold">Fusion complete — new fighter</h3><FighterCard fighter={fusionResult} /></div>}
    {!activeGroup ? <div className="space-y-4">{FUSION_RARITIES.map((mutation) => <section key={mutation}><h3 className="mb-2 text-lg font-black">{mutations[mutation].name}</h3><div className="grid gap-2 sm:grid-cols-3">{FUSION_SPECIES.map((crop) => { const group = groups.find((entry) => entry.mutation === mutation && entry.crop === crop)!; return <button key={`${mutation}:${crop}`} type="button" onClick={() => setOpenGroup({ mutation, crop })} className="rounded-xl border-2 border-[#765438]/25 bg-[#fff8dc] p-3 text-left hover:border-[#4f772d]"><strong>{mutations[mutation].name} {crops[crop].name}</strong><span className="mt-1 block text-xs">{group.ownedCount} owned</span><span className="block text-xs font-bold text-[#4f772d]">{mutation === "ascended" ? "Cannot fuse further" : `${group.fusionCount} fusion${group.fusionCount === 1 ? "" : "s"} available`}</span></button>; })}</div></section>)}</div> : <div><button type="button" onClick={() => setOpenGroup(null)} className="mb-3 rounded-lg border border-[#765438]/40 bg-[#fff8dc] px-3 py-2 text-sm font-bold">← All Fusion groups</button><h3 className="text-lg font-black">{mutations[activeGroup.mutation].name} {crops[activeGroup.crop].name}</h3><p className="mb-3 text-sm">{activeGroup.ownedCount} owned · {activeGroup.eligibleCount} unlocked and eligible</p>{activeGroup.fighters.length === 0 ? <p className="rounded-xl bg-[#fff8dc] p-4 text-sm">No fighters in this group.</p> : <div className="grid grid-cols-1 gap-3 sm:grid-cols-2">{activeGroup.fighters.map((fighter) => { const unavailable = fighter.locked || fighter.mutation === "ascended"; const chosen = selected.includes(fighter.id); return <FighterCard key={fighter.id} fighter={fighter} compact selectable selected={chosen} disabled={unavailable || (!chosen && selected.length === 4)} onSelect={toggleFighter} selectionLabel={fighter.locked ? "Locked · unavailable" : fighter.mutation === "ascended" ? "Ascended cannot fuse further" : chosen ? "Selected" : "Select fighter"} />; })}</div>}</div>}
    <div className="sticky bottom-0 mt-4 rounded-xl border-2 border-[#765438] bg-[#fff8dc]/95 p-3 text-sm shadow-xl backdrop-blur-sm"><div className="flex items-center justify-between gap-2"><strong>{selected.length} / 4 selected</strong><button type="button" onClick={clear} disabled={!selected.length} className="text-xs font-bold underline disabled:opacity-40">Clear</button></div><p className="font-bold">{firstSelected ? `${mutations[firstSelected.mutation].name} ${crops[firstSelected.crop].name}` : activeGroup ? `${mutations[activeGroup.mutation].name} ${crops[activeGroup.crop].name}` : "Choose a rarity and species"}</p>{firstSelected?.mutation === "prismatic" && <div className="flex items-center gap-1"><p className="text-xs font-bold">Ascension: {ascensionPity[firstSelected.crop] + 1} / {ASCENSION_HARD_PITY}{ascensionPity[firstSelected.crop] >= ASCENSION_HARD_PITY - 1 ? " · Next Ascension guaranteed" : ""}</p><HelpButton topic="ascension" onOpen={onHelp} label="Ascension pity" /></div>}{firstSelected && firstSelected.mutation !== "ascended" && <p className="text-xs">{firstSelected.mutation === "prismatic" && ascensionPity[firstSelected.crop] >= ASCENSION_HARD_PITY - 1 ? "100% Ascended" : `${Math.round((1 - FUSION_UPGRADE_CHANCE[firstSelected.mutation]) * 100)}% ${mutations[firstSelected.mutation].name} · ${Math.round(FUSION_UPGRADE_CHANCE[firstSelected.mutation] * 100)}% ${nextTier[firstSelected.mutation]}`}</p>}<button type="button" onClick={performFusion} disabled={!eligibility.valid} className="mt-2 w-full rounded-lg bg-[#4f772d] px-4 py-2 font-bold text-white disabled:cursor-not-allowed disabled:opacity-40">Fuse Fighters</button>{!eligibility.valid && selected.length > 0 && <p className="mt-1 text-xs text-[#7b3e20]">{eligibility.reason}</p>}</div>
  </div>;
}

function ReleaseConfirmation({ fighters, confirmation, onConfirm, onCancel }: { fighters: Fighter[]; confirmation: { fighterId: string; step: number }; onConfirm: () => void; onCancel: () => void }) {
  const fighter = fighters.find((entry) => entry.id === confirmation.fighterId); if (!fighter) return null;
  const finalStep = confirmation.step >= getReleaseConfirmationCount(fighter.mutation); const rare = fighter.mutation === "golden" || fighter.mutation === "prismatic" || fighter.mutation === "ascended";
  const warning = confirmation.step === 1 && getReleaseConfirmationCount(fighter.mutation) === 2 ? "This very rare fighter will be permanently removed. Continue to the final confirmation?" : fighter.mutation === "golden" ? "Golden fighters are rare. This permanently removes the fighter and gives no reward." : "This permanently removes the fighter and gives no reward.";
  return <div className="absolute inset-0 z-10 flex items-center justify-center bg-black/65 p-4" role="alertdialog" aria-modal="true"><div className="w-full max-w-sm rounded-xl border-2 border-[#765438] bg-[#fff8dc] p-5 shadow-2xl"><h3 className="text-lg font-black">Release {mutations[fighter.mutation].name} {crops[fighter.crop].name}?</h3><p className={`mt-2 text-sm ${rare ? "font-bold text-[#8b2f24]" : ""}`}>{warning}</p><div className="mt-4 flex gap-2"><button type="button" onClick={onConfirm} className="rounded-lg bg-[#8b2f24] px-3 py-2 font-bold text-white">{finalStep ? "Release permanently" : "Continue"}</button><button type="button" onClick={onCancel} className="rounded-lg border border-[#765438] px-3 py-2 font-bold">Cancel</button></div></div></div>;
}

function DismantleConfirmation({ fighters, confirmation, onConfirm, onCancel }: { fighters: Fighter[]; confirmation: { fighterId: string; step: number }; onConfirm: () => void; onCancel: () => void }) {
  const fighter = fighters.find((entry) => entry.id === confirmation.fighterId); if (!fighter) return null;
  const needsSecond = confirmation.step < getDismantleConfirmationCount(fighter.favorite);
  return <div className="absolute inset-0 z-10 flex items-center justify-center bg-black/65 p-4" role="alertdialog" aria-modal="true"><div className="w-full max-w-sm rounded-xl border-2 border-[#765438] bg-[#fff8dc] p-5 shadow-2xl"><h3 className="text-lg font-black">Dismantle {fighter.name || `Ascended ${crops[fighter.crop].name}`}?</h3><p className="mt-2 text-sm font-bold text-[#8b2f24]">This permanently removes the fighter and grants {ASCENDED_DISMANTLE_SHARDS} Ascendant Shard.</p>{fighter.favorite && <p className="mt-2 text-sm">This fighter is favorited. {needsSecond ? "Continue to the final confirmation." : "Final confirmation required."}</p>}<div className="mt-4 flex gap-2"><button type="button" onClick={onConfirm} className="rounded-lg bg-[#673a8f] px-3 py-2 font-bold text-white">{needsSecond ? "Continue" : "Dismantle permanently"}</button><button type="button" onClick={onCancel} className="rounded-lg border border-[#765438] px-3 py-2 font-bold">Cancel</button></div></div></div>;
}
